import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import { useState } from 'react'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import consulting from '../public/consulting.png'
import code from '../public/code.png'

import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'





export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Abhishek Bharti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-700' >
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons' >Abhishek</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer'
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li> 
              <li>
                <a 
                  className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8  '
                  href='#'
                  >
                    Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Abhishek Bharti</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Devloper and Problem Solver</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>
              Freelancer providing services like website, design and support, And looking for front-end Devloper role.
            </p>
            
          </div>

          <div className='text-5xl flex justify-center gap-16 text-gray-600'>
            <AiFillLinkedin />
            <AiFillTwitterCircle />
            <AiFillGithub />
          </div> 

          <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 mx-auto overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} />
          </div>
        </section>


        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
            Lorem Ipsum is simply <span className='text-teal-500'>dummy</span> text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
            </p>
          </div>

          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10' >
              <Image src={design} width={100} height={100} alt={"deisgn image"} className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8'>Beautiful Designs</h3>
              <p className='pt-8'> 
                Creating beautiful designs suited for your website
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I used</h4>
              <p >Canva</p>
              <p>Figma</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10' >
              <Image src={consulting} width={100} height={100} alt={"deisgn image"} className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8'>Beautiful Designs</h3>
              <p className='pt-8'> 
                Creating beautiful designs suited for your website
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I used</h4>
              <p >Canva</p>
              <p>Figma</p>
            </div>


            <div className='text-center shadow-lg p-10 rounded-xl my-10' >
              <Image src={code} width={100} height={100} alt={"deisgn image"} className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8'>Beautiful Designs</h3>
              <p className='pt-8'> 
                Creating beautiful designs suited for your website
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I used</h4>
              <p >Canva</p>
              <p>Figma</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'> Portfolio</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
              Freelancer providing services like website, design and support, And looking for front-end Devloper role.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800'>
            Lorem Ipsum is simply <span className='text-teal-500'>dummy</span> text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
            </p>
          </div>

          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className=' basis-1/3 flex-1 '  >
              <Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" alt="project Image"
               src={web1}/>
            </div>
            <div className=' basis-1/3 flex-1 '  >
              <Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" alt="project Image"
               src={web2}/>
            </div>
            <div className=' basis-1/3 flex-1 '  >
              <Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" alt="project Image"
               src={web3}/>
            </div>
            <div className=' basis-1/3 flex-1 '  >
              <Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" alt="project Image"
               src={web4}/>
            </div>
            <div className=' basis-1/3 flex-1 '  >
              <Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" alt="project Image"
               src={web5}/>
            </div>
            <div className=' basis-1/3 flex-1 '  >
              <Image className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive" alt="project Image"
               src={web6}/>
            </div>
          </div>
        </section>

      </main>
    </div>
  )
}
